// Global state management for Datawars.
// This module defines the initial player state and exposes a mutable
// `state` object that holds all game data. Other modules import
// and mutate the `state` as needed. A helper `resetState()` is
// provided to restore the player to a fresh game. Energy and hunger
// are tracked separately and range from 0–100.

// Initial values for the player's stats and possessions. Feel free
// to tweak these numbers to balance the early game.
export const INITIAL_PLAYER_STATE = {
  money: 1500,
  cred: 0,
  skills: {
    stealth: 1,
    speed: 1,
    power: 1
  },
  heat: 0,
  // Arsenal holds the names of purchased tools.
  arsenal: ['Basic Scanner'],
  // The player's deck holds mission modifiers (formerly action cards).
  deck: ['Time Compression'],
  // Inventory stores miscellaneous loot and consumables.
  inventory: [],
  // In‑game date. Days and months are kept simple (30 days per month).
  gameDate: {
    day: 2,
    month: 5,
    year: 2032
  },
  // Energy represents the player's stamina. Tasks and turns drain energy.
  energy: 100,
  // Hunger tracks nutritional needs. It slowly drops over time. Low hunger
  // will cause the player to pass out if ignored.
  hunger: 100,
  // Home upgrades and possessions. pcLevel affects the power of mission mods,
  // houseLevel affects sleep recovery, and pet is cosmetic for now.
  home: {
    pcLevel: 1,
    houseLevel: 1,
    pet: false
  }
};

// The central mutable state object. Modules import this and mutate its
// properties directly. Do not reassign `state` itself to ensure all
// references point to the same object.
export const state = {
  player: JSON.parse(JSON.stringify(INITIAL_PLAYER_STATE)),
  // A list of currently available missions. Each mission is an object
  // generated by the missions module.
  missions: [],
  // The mission that the player has selected and is currently working on.
  currentMission: null,
  // Running tasks are active operations against a mission target.
  runningTasks: [],
  // In‑game clock (0–23). Passing a turn advances the clock by 3 hours.
  gameTime: 9,
  // Reference to the interval timer used by the game loop. Null when idle.
  gameInterval: null
};

/**
 * Reset the game state back to its initial values. Any active
 * intervals are cleared. Use this when starting a new game or when
 * performing a `sudo reset-player` command.
 */
export function resetState() {
  state.player = JSON.parse(JSON.stringify(INITIAL_PLAYER_STATE));
  state.missions = [];
  state.currentMission = null;
  state.runningTasks = [];
  state.gameTime = 9;
  if (state.gameInterval) {
    clearInterval(state.gameInterval);
    state.gameInterval = null;
  }
}